// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bets.proto

package bets

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBetRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerAddress        string   `protobuf:"bytes,2,opt,name=player_address,json=playerAddress,proto3" json:"player_address,omitempty"`
	RefAddress           string   `protobuf:"bytes,3,opt,name=ref_address,json=refAddress,proto3" json:"ref_address,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	RollUnder            int32    `protobuf:"varint,5,opt,name=roll_under,json=rollUnder,proto3" json:"roll_under,omitempty"`
	Seed                 string   `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`
	CreateTrxHash        string   `protobuf:"bytes,7,opt,name=create_trx_hash,json=createTrxHash,proto3" json:"create_trx_hash,omitempty"`
	CreateTrxLt          int64    `protobuf:"varint,8,opt,name=create_trx_lt,json=createTrxLt,proto3" json:"create_trx_lt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBetRequest) Reset()         { *m = CreateBetRequest{} }
func (m *CreateBetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBetRequest) ProtoMessage()    {}
func (*CreateBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{0}
}

func (m *CreateBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBetRequest.Unmarshal(m, b)
}
func (m *CreateBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBetRequest.Marshal(b, m, deterministic)
}
func (m *CreateBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBetRequest.Merge(m, src)
}
func (m *CreateBetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBetRequest.Size(m)
}
func (m *CreateBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBetRequest proto.InternalMessageInfo

func (m *CreateBetRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *CreateBetRequest) GetPlayerAddress() string {
	if m != nil {
		return m.PlayerAddress
	}
	return ""
}

func (m *CreateBetRequest) GetRefAddress() string {
	if m != nil {
		return m.RefAddress
	}
	return ""
}

func (m *CreateBetRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateBetRequest) GetRollUnder() int32 {
	if m != nil {
		return m.RollUnder
	}
	return 0
}

func (m *CreateBetRequest) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *CreateBetRequest) GetCreateTrxHash() string {
	if m != nil {
		return m.CreateTrxHash
	}
	return ""
}

func (m *CreateBetRequest) GetCreateTrxLt() int64 {
	if m != nil {
		return m.CreateTrxLt
	}
	return 0
}

type CreateBetResponse struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateBetResponse) Reset()         { *m = CreateBetResponse{} }
func (m *CreateBetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBetResponse) ProtoMessage()    {}
func (*CreateBetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{1}
}

func (m *CreateBetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBetResponse.Unmarshal(m, b)
}
func (m *CreateBetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBetResponse.Marshal(b, m, deterministic)
}
func (m *CreateBetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBetResponse.Merge(m, src)
}
func (m *CreateBetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBetResponse.Size(m)
}
func (m *CreateBetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBetResponse proto.InternalMessageInfo

func (m *CreateBetResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateBetResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UpdateBetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId               int32    `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RandomRoll           int32    `protobuf:"varint,3,opt,name=random_roll,json=randomRoll,proto3" json:"random_roll,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	PlayerPayout         int64    `protobuf:"varint,5,opt,name=player_payout,json=playerPayout,proto3" json:"player_payout,omitempty"`
	RefPayout            int64    `protobuf:"varint,6,opt,name=ref_payout,json=refPayout,proto3" json:"ref_payout,omitempty"`
	ResolveTrxHash       string   `protobuf:"bytes,7,opt,name=resolve_trx_hash,json=resolveTrxHash,proto3" json:"resolve_trx_hash,omitempty"`
	ResolveTrxLt         int64    `protobuf:"varint,8,opt,name=resolve_trx_lt,json=resolveTrxLt,proto3" json:"resolve_trx_lt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBetRequest) Reset()         { *m = UpdateBetRequest{} }
func (m *UpdateBetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBetRequest) ProtoMessage()    {}
func (*UpdateBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{2}
}

func (m *UpdateBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBetRequest.Unmarshal(m, b)
}
func (m *UpdateBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBetRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBetRequest.Merge(m, src)
}
func (m *UpdateBetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBetRequest.Size(m)
}
func (m *UpdateBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBetRequest proto.InternalMessageInfo

func (m *UpdateBetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateBetRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *UpdateBetRequest) GetRandomRoll() int32 {
	if m != nil {
		return m.RandomRoll
	}
	return 0
}

func (m *UpdateBetRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *UpdateBetRequest) GetPlayerPayout() int64 {
	if m != nil {
		return m.PlayerPayout
	}
	return 0
}

func (m *UpdateBetRequest) GetRefPayout() int64 {
	if m != nil {
		return m.RefPayout
	}
	return 0
}

func (m *UpdateBetRequest) GetResolveTrxHash() string {
	if m != nil {
		return m.ResolveTrxHash
	}
	return ""
}

func (m *UpdateBetRequest) GetResolveTrxLt() int64 {
	if m != nil {
		return m.ResolveTrxLt
	}
	return 0
}

type UpdateBetResponse struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResolvedAt           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateBetResponse) Reset()         { *m = UpdateBetResponse{} }
func (m *UpdateBetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBetResponse) ProtoMessage()    {}
func (*UpdateBetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{3}
}

func (m *UpdateBetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBetResponse.Unmarshal(m, b)
}
func (m *UpdateBetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBetResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBetResponse.Merge(m, src)
}
func (m *UpdateBetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBetResponse.Size(m)
}
func (m *UpdateBetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBetResponse proto.InternalMessageInfo

func (m *UpdateBetResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateBetResponse) GetResolvedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ResolvedAt
	}
	return nil
}

type IsBetFetchedRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CreateTrxHash        string   `protobuf:"bytes,2,opt,name=create_trx_hash,json=createTrxHash,proto3" json:"create_trx_hash,omitempty"`
	CreateTrxLt          int64    `protobuf:"varint,3,opt,name=create_trx_lt,json=createTrxLt,proto3" json:"create_trx_lt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsBetFetchedRequest) Reset()         { *m = IsBetFetchedRequest{} }
func (m *IsBetFetchedRequest) String() string { return proto.CompactTextString(m) }
func (*IsBetFetchedRequest) ProtoMessage()    {}
func (*IsBetFetchedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{4}
}

func (m *IsBetFetchedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsBetFetchedRequest.Unmarshal(m, b)
}
func (m *IsBetFetchedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsBetFetchedRequest.Marshal(b, m, deterministic)
}
func (m *IsBetFetchedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsBetFetchedRequest.Merge(m, src)
}
func (m *IsBetFetchedRequest) XXX_Size() int {
	return xxx_messageInfo_IsBetFetchedRequest.Size(m)
}
func (m *IsBetFetchedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsBetFetchedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsBetFetchedRequest proto.InternalMessageInfo

func (m *IsBetFetchedRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *IsBetFetchedRequest) GetCreateTrxHash() string {
	if m != nil {
		return m.CreateTrxHash
	}
	return ""
}

func (m *IsBetFetchedRequest) GetCreateTrxLt() int64 {
	if m != nil {
		return m.CreateTrxLt
	}
	return 0
}

type IsBetFetchedResponse struct {
	Yes                  bool     `protobuf:"varint,1,opt,name=yes,proto3" json:"yes,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsBetFetchedResponse) Reset()         { *m = IsBetFetchedResponse{} }
func (m *IsBetFetchedResponse) String() string { return proto.CompactTextString(m) }
func (*IsBetFetchedResponse) ProtoMessage()    {}
func (*IsBetFetchedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{5}
}

func (m *IsBetFetchedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsBetFetchedResponse.Unmarshal(m, b)
}
func (m *IsBetFetchedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsBetFetchedResponse.Marshal(b, m, deterministic)
}
func (m *IsBetFetchedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsBetFetchedResponse.Merge(m, src)
}
func (m *IsBetFetchedResponse) XXX_Size() int {
	return xxx_messageInfo_IsBetFetchedResponse.Size(m)
}
func (m *IsBetFetchedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsBetFetchedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsBetFetchedResponse proto.InternalMessageInfo

func (m *IsBetFetchedResponse) GetYes() bool {
	if m != nil {
		return m.Yes
	}
	return false
}

func (m *IsBetFetchedResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type IsBetResolvedRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ResolveTrxHash       string   `protobuf:"bytes,2,opt,name=resolve_trx_hash,json=resolveTrxHash,proto3" json:"resolve_trx_hash,omitempty"`
	ResolveTrxLt         int64    `protobuf:"varint,3,opt,name=resolve_trx_lt,json=resolveTrxLt,proto3" json:"resolve_trx_lt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsBetResolvedRequest) Reset()         { *m = IsBetResolvedRequest{} }
func (m *IsBetResolvedRequest) String() string { return proto.CompactTextString(m) }
func (*IsBetResolvedRequest) ProtoMessage()    {}
func (*IsBetResolvedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{6}
}

func (m *IsBetResolvedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsBetResolvedRequest.Unmarshal(m, b)
}
func (m *IsBetResolvedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsBetResolvedRequest.Marshal(b, m, deterministic)
}
func (m *IsBetResolvedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsBetResolvedRequest.Merge(m, src)
}
func (m *IsBetResolvedRequest) XXX_Size() int {
	return xxx_messageInfo_IsBetResolvedRequest.Size(m)
}
func (m *IsBetResolvedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsBetResolvedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsBetResolvedRequest proto.InternalMessageInfo

func (m *IsBetResolvedRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *IsBetResolvedRequest) GetResolveTrxHash() string {
	if m != nil {
		return m.ResolveTrxHash
	}
	return ""
}

func (m *IsBetResolvedRequest) GetResolveTrxLt() int64 {
	if m != nil {
		return m.ResolveTrxLt
	}
	return 0
}

type IsBetResolvedResponse struct {
	Yes                  bool     `protobuf:"varint,1,opt,name=yes,proto3" json:"yes,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsBetResolvedResponse) Reset()         { *m = IsBetResolvedResponse{} }
func (m *IsBetResolvedResponse) String() string { return proto.CompactTextString(m) }
func (*IsBetResolvedResponse) ProtoMessage()    {}
func (*IsBetResolvedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{7}
}

func (m *IsBetResolvedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsBetResolvedResponse.Unmarshal(m, b)
}
func (m *IsBetResolvedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsBetResolvedResponse.Marshal(b, m, deterministic)
}
func (m *IsBetResolvedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsBetResolvedResponse.Merge(m, src)
}
func (m *IsBetResolvedResponse) XXX_Size() int {
	return xxx_messageInfo_IsBetResolvedResponse.Size(m)
}
func (m *IsBetResolvedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsBetResolvedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsBetResolvedResponse proto.InternalMessageInfo

func (m *IsBetResolvedResponse) GetYes() bool {
	if m != nil {
		return m.Yes
	}
	return false
}

func (m *IsBetResolvedResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateBetRequest)(nil), "bets.CreateBetRequest")
	proto.RegisterType((*CreateBetResponse)(nil), "bets.CreateBetResponse")
	proto.RegisterType((*UpdateBetRequest)(nil), "bets.UpdateBetRequest")
	proto.RegisterType((*UpdateBetResponse)(nil), "bets.UpdateBetResponse")
	proto.RegisterType((*IsBetFetchedRequest)(nil), "bets.IsBetFetchedRequest")
	proto.RegisterType((*IsBetFetchedResponse)(nil), "bets.IsBetFetchedResponse")
	proto.RegisterType((*IsBetResolvedRequest)(nil), "bets.IsBetResolvedRequest")
	proto.RegisterType((*IsBetResolvedResponse)(nil), "bets.IsBetResolvedResponse")
}

func init() { proto.RegisterFile("bets.proto", fileDescriptor_aa99872e6a2a7bdc) }

var fileDescriptor_aa99872e6a2a7bdc = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4b, 0x6f, 0xd3, 0x40,
	0x14, 0x85, 0x1b, 0x3b, 0x49, 0xeb, 0x9b, 0x07, 0xe9, 0x00, 0xad, 0x31, 0xa0, 0x46, 0xe6, 0xa1,
	0xac, 0x52, 0xa9, 0x6c, 0xa8, 0x90, 0x90, 0x12, 0x24, 0xa0, 0xa8, 0x0b, 0x34, 0x6a, 0xb7, 0x98,
	0x49, 0x7d, 0xf3, 0x90, 0x9c, 0xd8, 0xcc, 0x8c, 0x51, 0xc3, 0x86, 0x3d, 0x0b, 0xfe, 0x00, 0x7f,
	0x16, 0x79, 0xc6, 0x76, 0x9c, 0xc4, 0x55, 0xb3, 0xb3, 0xcf, 0x9c, 0x3b, 0x73, 0xe7, 0xbb, 0xc7,
	0x06, 0x18, 0xa1, 0x14, 0xfd, 0x88, 0x87, 0x32, 0x24, 0xd5, 0xe4, 0xd9, 0x39, 0x99, 0x84, 0xe1,
	0x24, 0xc0, 0x53, 0xa5, 0x8d, 0xe2, 0xf1, 0xa9, 0x9c, 0xcd, 0x51, 0x48, 0x36, 0x8f, 0xb4, 0xcd,
	0xfd, 0x63, 0x40, 0xe7, 0x03, 0x47, 0x26, 0x71, 0x88, 0x92, 0xe2, 0x8f, 0x18, 0x85, 0x24, 0xc7,
	0xb0, 0x3f, 0x61, 0x73, 0xf4, 0x66, 0xbe, 0x5d, 0xe9, 0x56, 0x7a, 0x35, 0x5a, 0x4f, 0x5e, 0x2f,
	0x7c, 0xf2, 0x0a, 0xda, 0x51, 0xc0, 0x96, 0xc8, 0x3d, 0xe6, 0xfb, 0x1c, 0x85, 0xb0, 0x8d, 0x6e,
	0xa5, 0x67, 0xd1, 0x96, 0x56, 0x07, 0x5a, 0x24, 0x27, 0xd0, 0xe0, 0x38, 0xce, 0x3d, 0xa6, 0xf2,
	0x00, 0xc7, 0x71, 0x66, 0x38, 0x82, 0x3a, 0x9b, 0x87, 0xf1, 0x42, 0xda, 0xd5, 0x6e, 0xa5, 0x67,
	0xd2, 0xf4, 0x8d, 0x3c, 0x07, 0xe0, 0x61, 0x10, 0x78, 0xf1, 0xc2, 0x47, 0x6e, 0xd7, 0xd4, 0xd9,
	0x56, 0xa2, 0x5c, 0x27, 0x02, 0x21, 0x50, 0x15, 0x88, 0xbe, 0x5d, 0x57, 0x1b, 0xaa, 0x67, 0xf2,
	0x1a, 0x1e, 0xdc, 0xa8, 0xfe, 0x3d, 0xc9, 0x6f, 0xbd, 0x29, 0x13, 0x53, 0x7b, 0x5f, 0xf7, 0xa4,
	0xe5, 0x2b, 0x7e, 0xfb, 0x99, 0x89, 0x29, 0x71, 0xa1, 0x55, 0xf0, 0x05, 0xd2, 0x3e, 0x50, 0x27,
	0x37, 0x72, 0xd7, 0xa5, 0x74, 0xbf, 0xc1, 0x61, 0x81, 0x85, 0x88, 0xc2, 0x85, 0x40, 0xd2, 0x06,
	0x23, 0xe5, 0x60, 0x52, 0x63, 0xe6, 0x93, 0x73, 0x00, 0x5d, 0xe3, 0x7b, 0x4c, 0xaa, 0xfb, 0x37,
	0xce, 0x9c, 0xbe, 0xe6, 0xdc, 0xcf, 0x38, 0xf7, 0xaf, 0x32, 0xce, 0xd4, 0x4a, 0xdd, 0x03, 0xe9,
	0xfe, 0x35, 0xa0, 0x73, 0x1d, 0xf9, 0xeb, 0xb0, 0x57, 0xfb, 0xd7, 0xd4, 0xfe, 0x05, 0xf8, 0xc6,
	0x1a, 0xfc, 0x84, 0x2a, 0x5b, 0xf8, 0xe1, 0xdc, 0x4b, 0x88, 0x28, 0xaa, 0x35, 0x0a, 0x5a, 0xa2,
	0x61, 0x10, 0x90, 0x67, 0x60, 0x89, 0xd9, 0x64, 0xc1, 0x64, 0xcc, 0x51, 0x81, 0xb5, 0xe8, 0x4a,
	0x20, 0x2f, 0x20, 0x9d, 0x92, 0x17, 0xb1, 0x65, 0x18, 0x4b, 0x85, 0xd7, 0xa4, 0x4d, 0x2d, 0x7e,
	0x55, 0x9a, 0x1a, 0x00, 0x8e, 0x33, 0x47, 0x5d, 0x39, 0x2c, 0x8e, 0xe3, 0x74, 0xb9, 0x07, 0x1d,
	0x8e, 0x22, 0x0c, 0x7e, 0x6e, 0xd1, 0x6e, 0xa7, 0x7a, 0x86, 0xfb, 0x25, 0xb4, 0x8b, 0xce, 0x9c,
	0x77, 0x73, 0xe5, 0xbb, 0x94, 0xee, 0x77, 0x38, 0x2c, 0xf0, 0xb8, 0x03, 0xf8, 0xbb, 0x24, 0x4d,
	0xaa, 0x68, 0x47, 0xe2, 0x90, 0xd9, 0x07, 0xd2, 0xfd, 0x05, 0x0f, 0x2f, 0xc4, 0x10, 0xe5, 0x47,
	0x94, 0x37, 0x53, 0xf4, 0xef, 0x4d, 0x78, 0x49, 0x9c, 0x8c, 0x9d, 0xe2, 0x64, 0x6e, 0xc7, 0xe9,
	0x2d, 0x3c, 0x5a, 0x3f, 0x3b, 0xbd, 0x60, 0x07, 0xcc, 0x25, 0x0a, 0x75, 0xf0, 0x01, 0x4d, 0x1e,
	0xd3, 0x2b, 0x1b, 0x59, 0x06, 0xdc, 0xdf, 0x69, 0x25, 0x4d, 0x2f, 0x72, 0x6f, 0xdb, 0x65, 0x83,
	0x31, 0x76, 0x1c, 0x8c, 0x59, 0x32, 0x98, 0x73, 0x78, 0xbc, 0xd1, 0xc0, 0xae, 0xbd, 0x9f, 0xfd,
	0x33, 0xa0, 0x3a, 0x44, 0x29, 0xc8, 0x7b, 0xb0, 0xf2, 0xaf, 0x89, 0x1c, 0xf5, 0xd5, 0xbf, 0x69,
	0xf3, 0x57, 0xe3, 0x1c, 0x6f, 0xe9, 0xfa, 0x20, 0x77, 0x2f, 0xa9, 0xcf, 0xc3, 0x91, 0xd5, 0x6f,
	0x7e, 0x3d, 0x59, 0xfd, 0x56, 0x8a, 0xdc, 0x3d, 0xf2, 0x09, 0x9a, 0x45, 0xfc, 0xe4, 0x89, 0xb6,
	0x96, 0xc4, 0xc1, 0x71, 0xca, 0x96, 0xf2, 0x8d, 0xbe, 0x40, 0x6b, 0x0d, 0x06, 0x29, 0xda, 0x37,
	0x46, 0xe4, 0x3c, 0x2d, 0x5d, 0xcb, 0xf6, 0x1a, 0xd5, 0x55, 0x5e, 0xdf, 0xfc, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0xec, 0xaa, 0x90, 0x9c, 0xab, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BetsClient is the client API for Bets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BetsClient interface {
	CreateBet(ctx context.Context, in *CreateBetRequest, opts ...grpc.CallOption) (*CreateBetResponse, error)
	UpdateBet(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error)
	IsBetFetched(ctx context.Context, in *IsBetFetchedRequest, opts ...grpc.CallOption) (*IsBetFetchedResponse, error)
	IsBetResolved(ctx context.Context, in *IsBetResolvedRequest, opts ...grpc.CallOption) (*IsBetResolvedResponse, error)
}

type betsClient struct {
	cc grpc.ClientConnInterface
}

func NewBetsClient(cc grpc.ClientConnInterface) BetsClient {
	return &betsClient{cc}
}

func (c *betsClient) CreateBet(ctx context.Context, in *CreateBetRequest, opts ...grpc.CallOption) (*CreateBetResponse, error) {
	out := new(CreateBetResponse)
	err := c.cc.Invoke(ctx, "/bets.Bets/CreateBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *betsClient) UpdateBet(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error) {
	out := new(UpdateBetResponse)
	err := c.cc.Invoke(ctx, "/bets.Bets/UpdateBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *betsClient) IsBetFetched(ctx context.Context, in *IsBetFetchedRequest, opts ...grpc.CallOption) (*IsBetFetchedResponse, error) {
	out := new(IsBetFetchedResponse)
	err := c.cc.Invoke(ctx, "/bets.Bets/IsBetFetched", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *betsClient) IsBetResolved(ctx context.Context, in *IsBetResolvedRequest, opts ...grpc.CallOption) (*IsBetResolvedResponse, error) {
	out := new(IsBetResolvedResponse)
	err := c.cc.Invoke(ctx, "/bets.Bets/IsBetResolved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BetsServer is the server API for Bets service.
type BetsServer interface {
	CreateBet(context.Context, *CreateBetRequest) (*CreateBetResponse, error)
	UpdateBet(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error)
	IsBetFetched(context.Context, *IsBetFetchedRequest) (*IsBetFetchedResponse, error)
	IsBetResolved(context.Context, *IsBetResolvedRequest) (*IsBetResolvedResponse, error)
}

// UnimplementedBetsServer can be embedded to have forward compatible implementations.
type UnimplementedBetsServer struct {
}

func (*UnimplementedBetsServer) CreateBet(ctx context.Context, req *CreateBetRequest) (*CreateBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBet not implemented")
}
func (*UnimplementedBetsServer) UpdateBet(ctx context.Context, req *UpdateBetRequest) (*UpdateBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBet not implemented")
}
func (*UnimplementedBetsServer) IsBetFetched(ctx context.Context, req *IsBetFetchedRequest) (*IsBetFetchedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsBetFetched not implemented")
}
func (*UnimplementedBetsServer) IsBetResolved(ctx context.Context, req *IsBetResolvedRequest) (*IsBetResolvedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsBetResolved not implemented")
}

func RegisterBetsServer(s *grpc.Server, srv BetsServer) {
	s.RegisterService(&_Bets_serviceDesc, srv)
}

func _Bets_CreateBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetsServer).CreateBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bets.Bets/CreateBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetsServer).CreateBet(ctx, req.(*CreateBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bets_UpdateBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetsServer).UpdateBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bets.Bets/UpdateBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetsServer).UpdateBet(ctx, req.(*UpdateBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bets_IsBetFetched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBetFetchedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetsServer).IsBetFetched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bets.Bets/IsBetFetched",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetsServer).IsBetFetched(ctx, req.(*IsBetFetchedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bets_IsBetResolved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBetResolvedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetsServer).IsBetResolved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bets.Bets/IsBetResolved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetsServer).IsBetResolved(ctx, req.(*IsBetResolvedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bets.Bets",
	HandlerType: (*BetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBet",
			Handler:    _Bets_CreateBet_Handler,
		},
		{
			MethodName: "UpdateBet",
			Handler:    _Bets_UpdateBet_Handler,
		},
		{
			MethodName: "IsBetFetched",
			Handler:    _Bets_IsBetFetched_Handler,
		},
		{
			MethodName: "IsBetResolved",
			Handler:    _Bets_IsBetResolved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bets.proto",
}
