// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bets.proto

package bets

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBetRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerAddress        string   `protobuf:"bytes,2,opt,name=player_address,json=playerAddress,proto3" json:"player_address,omitempty"`
	RefAddress           string   `protobuf:"bytes,3,opt,name=ref_address,json=refAddress,proto3" json:"ref_address,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	RollUnder            int32    `protobuf:"varint,5,opt,name=roll_under,json=rollUnder,proto3" json:"roll_under,omitempty"`
	RandomRoll           int32    `protobuf:"varint,6,opt,name=random_roll,json=randomRoll,proto3" json:"random_roll,omitempty"`
	Seed                 string   `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	PlayerPayout         int64    `protobuf:"varint,9,opt,name=player_payout,json=playerPayout,proto3" json:"player_payout,omitempty"`
	RefPayout            int64    `protobuf:"varint,10,opt,name=ref_payout,json=refPayout,proto3" json:"ref_payout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBetRequest) Reset()         { *m = CreateBetRequest{} }
func (m *CreateBetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBetRequest) ProtoMessage()    {}
func (*CreateBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{0}
}

func (m *CreateBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBetRequest.Unmarshal(m, b)
}
func (m *CreateBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBetRequest.Marshal(b, m, deterministic)
}
func (m *CreateBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBetRequest.Merge(m, src)
}
func (m *CreateBetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBetRequest.Size(m)
}
func (m *CreateBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBetRequest proto.InternalMessageInfo

func (m *CreateBetRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *CreateBetRequest) GetPlayerAddress() string {
	if m != nil {
		return m.PlayerAddress
	}
	return ""
}

func (m *CreateBetRequest) GetRefAddress() string {
	if m != nil {
		return m.RefAddress
	}
	return ""
}

func (m *CreateBetRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateBetRequest) GetRollUnder() int32 {
	if m != nil {
		return m.RollUnder
	}
	return 0
}

func (m *CreateBetRequest) GetRandomRoll() int32 {
	if m != nil {
		return m.RandomRoll
	}
	return 0
}

func (m *CreateBetRequest) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *CreateBetRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CreateBetRequest) GetPlayerPayout() int64 {
	if m != nil {
		return m.PlayerPayout
	}
	return 0
}

func (m *CreateBetRequest) GetRefPayout() int64 {
	if m != nil {
		return m.RefPayout
	}
	return 0
}

type CreateBetResponse struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateBetResponse) Reset()         { *m = CreateBetResponse{} }
func (m *CreateBetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBetResponse) ProtoMessage()    {}
func (*CreateBetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa99872e6a2a7bdc, []int{1}
}

func (m *CreateBetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBetResponse.Unmarshal(m, b)
}
func (m *CreateBetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBetResponse.Marshal(b, m, deterministic)
}
func (m *CreateBetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBetResponse.Merge(m, src)
}
func (m *CreateBetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBetResponse.Size(m)
}
func (m *CreateBetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBetResponse proto.InternalMessageInfo

func (m *CreateBetResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateBetResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateBetRequest)(nil), "bets.CreateBetRequest")
	proto.RegisterType((*CreateBetResponse)(nil), "bets.CreateBetResponse")
}

func init() { proto.RegisterFile("bets.proto", fileDescriptor_aa99872e6a2a7bdc) }

var fileDescriptor_aa99872e6a2a7bdc = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x2b, 0x59, 0x96, 0xab, 0x71, 0x6b, 0xda, 0x3d, 0xd8, 0x8b, 0x69, 0xb1, 0x71, 0x29,
	0xf8, 0x24, 0x83, 0x7b, 0xea, 0x25, 0x60, 0x07, 0x02, 0xb9, 0x05, 0x91, 0x5c, 0x23, 0xd6, 0xd9,
	0x91, 0x10, 0x48, 0x5a, 0x65, 0x77, 0x75, 0xf0, 0xe3, 0xe5, 0xcd, 0x82, 0x66, 0x25, 0x27, 0x24,
	0xb7, 0x9d, 0x6f, 0x3e, 0x76, 0x86, 0xf9, 0x01, 0x4e, 0x68, 0x4d, 0xdc, 0x68, 0x65, 0x15, 0x0b,
	0xba, 0xf7, 0x72, 0x95, 0x2b, 0x95, 0x97, 0xb8, 0x23, 0x76, 0x6a, 0xb3, 0x9d, 0x2d, 0x2a, 0x34,
	0x56, 0x54, 0x8d, 0xd3, 0x36, 0x2f, 0x3e, 0xfc, 0xb8, 0xd6, 0x28, 0x2c, 0x1e, 0xd1, 0x26, 0xf8,
	0xdc, 0xa2, 0xb1, 0x6c, 0x01, 0x93, 0x5c, 0x54, 0x98, 0x16, 0x92, 0x7b, 0x6b, 0x6f, 0x3b, 0x4e,
	0xc2, 0xae, 0xbc, 0x95, 0xec, 0x2f, 0xcc, 0x9a, 0x52, 0x9c, 0x51, 0xa7, 0x42, 0x4a, 0x8d, 0xc6,
	0x70, 0x7f, 0xed, 0x6d, 0xa3, 0xe4, 0xbb, 0xa3, 0x07, 0x07, 0xd9, 0x0a, 0xa6, 0x1a, 0xb3, 0x8b,
	0x33, 0x22, 0x07, 0x34, 0x66, 0x83, 0x30, 0x87, 0x50, 0x54, 0xaa, 0xad, 0x2d, 0x0f, 0xd6, 0xde,
	0x76, 0x94, 0xf4, 0x15, 0xfb, 0x0d, 0xa0, 0x55, 0x59, 0xa6, 0x6d, 0x2d, 0x51, 0xf3, 0x31, 0xcd,
	0x8e, 0x3a, 0xf2, 0xd0, 0x01, 0xfa, 0x57, 0xd4, 0x52, 0x55, 0x69, 0xc7, 0x78, 0x48, 0x7d, 0x70,
	0x28, 0x51, 0x65, 0xc9, 0x18, 0x04, 0x06, 0x51, 0xf2, 0x09, 0x4d, 0xa4, 0x37, 0xfb, 0x05, 0x91,
	0x29, 0xf2, 0x5a, 0xd8, 0x56, 0x23, 0xff, 0x4a, 0x8d, 0x37, 0xc0, 0xfe, 0x40, 0xbf, 0x7b, 0xda,
	0x88, 0xb3, 0x6a, 0x2d, 0x8f, 0x68, 0xa1, 0x6f, 0x0e, 0xde, 0x11, 0xa3, 0xb5, 0x30, 0x1b, 0x0c,
	0x20, 0x23, 0xd2, 0x98, 0xb9, 0xf6, 0xe6, 0x11, 0x7e, 0xbe, 0x3b, 0xa1, 0x69, 0x54, 0x6d, 0x90,
	0xcd, 0xc0, 0xef, 0xcf, 0x37, 0x4a, 0xfc, 0x42, 0xb2, 0xff, 0x00, 0x4f, 0x24, 0xc9, 0x54, 0x58,
	0x3a, 0xdb, 0x74, 0xbf, 0x8c, 0x5d, 0x3c, 0xf1, 0x10, 0x4f, 0x7c, 0x3f, 0xc4, 0x93, 0x44, 0xbd,
	0x7d, 0xb0, 0xfb, 0x1b, 0x08, 0x8e, 0x68, 0x0d, 0xbb, 0x82, 0xe8, 0x32, 0x87, 0xcd, 0x63, 0x0a,
	0xfb, 0x63, 0x76, 0xcb, 0xc5, 0x27, 0xee, 0x16, 0xda, 0x7c, 0x39, 0x85, 0x34, 0xe6, 0xdf, 0x6b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0x9a, 0x9e, 0xc2, 0x27, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BetsClient is the client API for Bets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BetsClient interface {
	CreateBet(ctx context.Context, in *CreateBetRequest, opts ...grpc.CallOption) (*CreateBetResponse, error)
}

type betsClient struct {
	cc grpc.ClientConnInterface
}

func NewBetsClient(cc grpc.ClientConnInterface) BetsClient {
	return &betsClient{cc}
}

func (c *betsClient) CreateBet(ctx context.Context, in *CreateBetRequest, opts ...grpc.CallOption) (*CreateBetResponse, error) {
	out := new(CreateBetResponse)
	err := c.cc.Invoke(ctx, "/bets.Bets/CreateBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BetsServer is the server API for Bets service.
type BetsServer interface {
	CreateBet(context.Context, *CreateBetRequest) (*CreateBetResponse, error)
}

// UnimplementedBetsServer can be embedded to have forward compatible implementations.
type UnimplementedBetsServer struct {
}

func (*UnimplementedBetsServer) CreateBet(ctx context.Context, req *CreateBetRequest) (*CreateBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBet not implemented")
}

func RegisterBetsServer(s *grpc.Server, srv BetsServer) {
	s.RegisterService(&_Bets_serviceDesc, srv)
}

func _Bets_CreateBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetsServer).CreateBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bets.Bets/CreateBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetsServer).CreateBet(ctx, req.(*CreateBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bets.Bets",
	HandlerType: (*BetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBet",
			Handler:    _Bets_CreateBet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bets.proto",
}
